### ISSUE TITLE
error  displaying

### ISSUE THREAD

**Issue by AbdishakurAbdiSaidAdan** [hmgtech/Covid-19-Detector-with-Flask#1]
C:\Users\theatm\Documents\Covid-19-Detector-with-Flask-main> python app1.py
      Using TensorFlow backend.
      C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
    packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 
     deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
        _np_qint8 = np.dtype([("qint8", np.int8, 1)])
      C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
    packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 
    deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
        _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
      C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
    packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 
    deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
        _np_qint16 = np.dtype([("qint16", np.int16, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: 
    FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be 
     understood as (type, (1,)) / '(1,)type'.
      _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:520: 
      FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be 
      understood as (type, (1,)) / '(1,)type'.
      _np_qint32 = np.dtype([("qint32", np.int32, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:525: 
    FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be 
   understood as (type, (1,)) / '(1,)type'.
    np_resource = np.dtype([("resource", np.ubyte, 1)])
   C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
   packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
   type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
      _np_qint8 = np.dtype([("qint8", np.int8, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
       packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
     type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
      _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
       packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
     type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
  packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
    type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
    C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
    packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
    type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
   C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site- 
   packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of 
   type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
    Traceback (most recent call last):
    File "app1.py", line 27, in <module>
    model = load_model(MODEL_PATH)
    File "C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\models.py", line 243, in 
    load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
   File "C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\models.py", line 317, in 
    model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\__init__.py", line 55, in 
   deserialize
    printable_module_name='layer')
   File "C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\generic_utils.py", line 143, in 
    deserialize_keras_object
    list(custom_objects.items())))
   File "C:\Users\theatm\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\models.py", line 1347, in 
   from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
   KeyError: 0

**Comment by AbdishakurAbdiSaidAdan** [comment]
please look into 

keyError:0
